### ISSUE TITLE
InvalidOperationException("You must attach an event handler to the event signal within a reasonable amount of time.")

### ISSUE THREAD

**Issue by WalterW** [jenyayel/SignalR.Client.20#3] opened 2015-03-25 16:25 UTC
hi there,

I'm using the library and test in Unity3D player is fine. But once I deployed to my Windows Phone, the problem occur. Any idea?

thank you

from
Walter

**Comment by jenyayel** [comment] 2015-03-26 07:28
Hi,

I never had a chance to run it under WP. Can you provide a stacktrace? 

Thanks.

**Comment by WalterW** [comment] 2015-03-27 06:47
looks like it went into maximum try to connect and failed..... do you have any idea in your mind? Below is the Debug log I able to grab 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/WP8/runtime/UnityEngineDebug.gen.cpp Line: 62)



¡@


6


 


(Filename: C:/buildslave/unity/build/artifacts/generated/WP8/runtime/UnityEngineDebug.gen.cpp Line: 62)



¡@


GetResponseCallback: error occurred - You must attach an event handler to the event signal within a reasonable amount of time.


OnFinish


 


(Filename: C:/buildslave/unity/build/artifacts/generated/WP8/runtime/UnityEngineDebug.gen.cpp Line: 62)



¡@


OnFinish


 


(Filename: C:/buildslave/unity/build/artifacts/generated/WP8/runtime/UnityEngineDebug.gen.cpp Line: 62)



¡@


Failed to read response: System.NullReferenceException: Object reference not set to an instance of an object.


   at SignalR.Client._20.Http.HttpHelper.ReadAsString(HttpWebResponse response)


6
 
 
 
 
thank you
 
from
Walter
 

 
Date: Thu, 26 Mar 2015 00:28:15 -0700

**Comment by jenyayel** [comment] 2015-03-30 17:32
Based on your callstack the problem is that HttpWebResponse is null. If I remember right, on WP you are running not on Mono, you are targeting PCL. Can you debug DefaultHttpClient and see which parameters are passed when Finished event raised?

**Comment by WalterW** [comment] 2015-04-01 07:59
hi there
 
Can I know what I should look for? I know the line which it instantiate the object - Connection.cs.
 
refer the attachment

 
Date: Mon, 30 Mar 2015 10:32:10 -0700

**Comment by jenyayel** [comment] 2015-04-01 20:08
There is no attachment.

Add breakpoint in [DefaultHttpClient] (https://github.com/jenyayel/SignalR.Client.20/blob/master/source/SignalR.Client.20/Http/DefaultHttpClient.cs) at line 14 and 18. See what happens and let me know.

**Comment by WalterW** [comment] 2015-04-06 15:41
hi there,
 
Below is the value I got when I got.  Is there any specific property you want me to check?
 
UnityEngine.Debug.Log(string.Format("EventSignal: {0}", _signal.GetType().ToString()));
EventSignal: SignalR.Client._20.Transports.EventSignal`1[SignalR.Client._20.Http.CallbackDetail`1[System.Net.HttpWebResponse]]
 
 
UnityEngine.Debug.Log(string.Format("EventSignal: {0}", _returnSignal.GetType().ToString()));
EventSignal: SignalR.Client._20.Transports.EventSignal`1[SignalR.Client._20.Http.IResponse]
 
 
 
thank you
 
from
Walter
 
Date: Wed, 1 Apr 2015 13:08:43 -0700

**Comment by jenyayel** [comment] 2016-11-22 08:32
Are you still having troubles with it or we can close this issue?

**Closed** 2017-01-18 19:25 UTC
